version: '3.8'

version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - media:/app/media
    environment:
      - PYTHONUNBUFFERED=1


volumes:
  staticfiles:
  media: