version: '3.8'

services:
  web:
    build: .
    restart: always
    network_mode: "host"  # Добавляем эту строку
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  static_volume:
  media_volume: