version: '3.8'

version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - media:/app/media
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db  # Уберите эту строку, если больше не используете db

volumes:
  staticfiles:
  media: